import { defineConfig } from 'oxfmt'

export default defineConfig({
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  bracketSpacing: true,
  arrowParens: 'always',
  endOfLine: 'lf',
  ignorePatterns: [
    '*.min.js',
    '*.min.css',
    '*.tsbuildinfo',
    '**/*.md',
    '**/*.gen.ts',
    '**/*.gen.tsx',
    'registry/public/**',
    'registry/variants/registry.json',
    'registry/variants/source/**',
    'registry/variants/support/**',
    'registry/themes/*.css',
    'registry/themes/registry.json',
    'playground/test-results/**',
    'playground/playwright-report/**',
    'artifacts/playground/**',
    'tooling/upstream/providers/**',
    'packages/ui/src/theme/preflight.css',
    'packages/ui/src/theme/shadcn-tailwind.css',
  ],
  sortImports: {
    groups: [
      'type-import',
      ['value-builtin', 'value-external'],
      'type-internal',
      'value-internal',
      ['type-parent', 'type-sibling', 'type-index'],
      ['value-parent', 'value-sibling', 'value-index'],
      'unknown',
    ],
  },
})
