export const componentGroups = [
  {
    id: 'actions-inputs',
    label: 'Actions & inputs',
    components: [
      'button',
      'button-group',
      'checkbox',
      'field',
      'input',
      'input-group',
      'input-otp',
      'label',
      'native-select',
      'radio-group',
      'select',
      'slider',
      'switch',
      'textarea',
      'toggle',
      'toggle-group',
    ],
  },
  {
    id: 'content-feedback',
    label: 'Content & feedback',
    components: [
      'alert',
      'aspect-ratio',
      'avatar',
      'badge',
      'card',
      'empty',
      'item',
      'kbd',
      'progress',
      'separator',
      'skeleton',
      'spinner',
      'table',
      'toast',
    ],
  },
  {
    id: 'navigation-layout',
    label: 'Navigation & layout',
    components: [
      'accordion',
      'breadcrumb',
      'collapsible',
      'direction',
      'navigation-menu',
      'pagination',
      'resizable',
      'scroll-area',
      'tabs',
    ],
  },
  {
    id: 'menus-overlays',
    label: 'Menus & overlays',
    components: [
      'alert-dialog',
      'command',
      'context-menu',
      'dialog',
      'drawer',
      'dropdown-menu',
      'hover-card',
      'menubar',
      'popover',
      'sheet',
      'tooltip',
    ],
  },
] as const

export const registryComponents = [
  'attachment',
  'bubble',
  'calendar',
  'carousel',
  'chart',
  'combobox',
  'marker',
  'message',
  'message-scroller',
  'questionnaire',
  'sidebar',
  'sonner',
] as const

export const componentSources = {
  'component/accordion': '@shadcn/accordion',
  'component/alert': '@shadcn/alert',
  'component/alert-dialog': '@shadcn/alert-dialog',
  'component/aspect-ratio': '@shadcn/aspect-ratio',
  'component/attachment': '@shadcn/attachment',
  'component/avatar': '@shadcn/avatar',
  'component/badge': '@shadcn/badge',
  'component/breadcrumb': '@shadcn/breadcrumb',
  'component/bubble': '@shadcn/bubble',
  'component/button': '@shadcn/button',
  'component/button-group': '@shadcn/button-group',
  'component/calendar': '@shadcn/calendar',
  'component/card': '@shadcn/card',
  'component/carousel': '@shadcn/carousel',
  'component/chart': '@shadcn/chart',
  'component/checkbox': '@shadcn/checkbox',
  'component/collapsible': '@shadcn/collapsible',
  'component/combobox': '@shadcn/combobox',
  'component/command': '@shadcn/command',
  'component/context-menu': '@shadcn/context-menu',
  'component/dialog': '@shadcn/dialog',
  'component/direction': '@shadcn/direction',
  'component/drawer': '@shadcn/drawer',
  'component/dropdown-menu': '@shadcn/dropdown-menu',
  'component/empty': '@shadcn/empty',
  'component/field': '@shadcn/field',
  'component/hover-card': '@shadcn/hover-card',
  'component/input': '@shadcn/input',
  'component/input-group': '@shadcn/input-group',
  'component/input-otp': '@shadcn/input-otp',
  'component/item': '@shadcn/item',
  'component/kbd': '@shadcn/kbd',
  'component/label': '@shadcn/label',
  'component/marker': '@shadcn/marker',
  'component/menubar': '@shadcn/menubar',
  'component/message': '@shadcn/message',
  'component/message-scroller': '@shadcn/message-scroller',
  'component/native-select': '@shadcn/native-select',
  'component/navigation-menu': '@shadcn/navigation-menu',
  'component/pagination': '@shadcn/pagination',
  'component/popover': '@shadcn/popover',
  'component/progress': '@shadcn/progress',
  'component/questionnaire': '@shadcn/questionnaire',
  'component/radio-group': '@shadcn/radio-group',
  'component/resizable': '@shadcn/resizable',
  'component/scroll-area': '@shadcn/scroll-area',
  'component/select': '@shadcn/select',
  'component/separator': '@shadcn/separator',
  'component/sheet': '@shadcn/sheet',
  'component/sidebar': '@shadcn/sidebar',
  'component/skeleton': '@shadcn/skeleton',
  'component/slider': '@shadcn/slider',
  'component/sonner': '@shadcn/sonner',
  'component/spinner': '@shadcn/spinner',
  'component/switch': '@shadcn/switch',
  'component/table': '@shadcn/table',
  'component/tabs': '@shadcn/tabs',
  'component/textarea': '@shadcn/textarea',
  'component/toast': '@shadcn/toast',
  'component/toggle': '@shadcn/toggle',
  'component/toggle-group': '@shadcn/toggle-group',
  'component/tooltip': '@shadcn/tooltip',
} as const

export const runtimeComponentNames = componentGroups.flatMap((group) => group.components)
export const componentNames = [...runtimeComponentNames, ...registryComponents]
