export const componentGroups = [
  {
    id: 'actions-inputs',
    label: 'Actions & inputs',
    components: [
      'button',
      'button-group',
      'checkbox',
      'field',
      'input',
      'input-group',
      'input-otp',
      'label',
      'native-select',
      'radio-group',
      'select',
      'slider',
      'switch',
      'textarea',
      'toggle',
      'toggle-group',
    ],
  },
  {
    id: 'content-feedback',
    label: 'Content & feedback',
    components: [
      'alert',
      'aspect-ratio',
      'avatar',
      'badge',
      'card',
      'empty',
      'item',
      'kbd',
      'progress',
      'separator',
      'skeleton',
      'spinner',
      'table',
      'toast',
    ],
  },
  {
    id: 'navigation-layout',
    label: 'Navigation & layout',
    components: [
      'accordion',
      'breadcrumb',
      'collapsible',
      'direction',
      'navigation-menu',
      'pagination',
      'resizable',
      'scroll-area',
      'tabs',
    ],
  },
  {
    id: 'menus-overlays',
    label: 'Menus & overlays',
    components: [
      'alert-dialog',
      'command',
      'context-menu',
      'dialog',
      'drawer',
      'dropdown-menu',
      'hover-card',
      'menubar',
      'popover',
      'sheet',
      'tooltip',
    ],
  },
] as const

export const registryComponents = [
  'attachment',
  'bubble',
  'calendar',
  'carousel',
  'chart',
  'combobox',
  'marker',
  'message',
  'message-scroller',
  'questionnaire',
  'sidebar',
  'sonner',
] as const

export const runtimeComponentNames = componentGroups.flatMap((group) => group.components)
export const componentNames = [...runtimeComponentNames, ...registryComponents]
