name: Publish

on:
  push:
    branches: [main]
    paths:
      - '.release-please-manifest.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astrale-os/config/.github/actions/publish/packages@e0a84a92c9da33aa9046847ca2d32e785a06ec75
        with:
          dirs: 'constants utils styles preset components ui'
          github-token: ${{ github.token }}
          build-command: pnpm build
